version: '3.8'

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MySecureThesisPassword123!
      POSTGRES_DB: academicsentinel
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Username=postgres;Password=MySecureThesisPassword123!;Database=academicsentinel;Ssl Mode=Disable;
      - Jwt__Key=YourSuperSecretJwtKeyForThesis2026!
      - ASPNETCORE_ENVIRONMENT=Production
      - CLOUDINARY_URL=cloudinary://364994355236151:S6dpKkyimggZmNWkK16kg_bNSGs@dhhaflmqu
    depends_on:
      - db

volumes:
  pgdata:
